### ISSUE TITLE
frida run error:_frida.so: undefined symbol: PyUnicodeUCS2_AsUTF8String

### ISSUE THREAD

**Issue by ling245100108** [frida/frida-website#18] opened 2015-04-12 11:06 UTC
I run the python example in ubuntu 14.04. the following is the error. I don't know how to solve it. Can you give me a hand?

***
Failed to load the Frida native extension: /home/ling/.python-eggs/frida-3.0.1-py2.7-linux-x86_64.egg-tmp/_frida.so: undefined symbol: PyUnicodeUCS2_AsUTF8String
Please ensure that the extension was compiled for Python 2.7.
***

Traceback (most recent call last):
  File "../../PycharmProjects/untitled/frida_test/example.py", line 2, in <module>
    session = frida.attach('cat')
  File "/usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-x86_64.egg/frida/__init__.py", line 16, in attach
  File "/usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-x86_64.egg/frida/__init__.py", line 84, in get_device_manager
ImportError: /home/ling/.python-eggs/frida-3.0.1-py2.7-linux-x86_64.egg-tmp/_frida.so: undefined symbol: PyUnicodeUCS2_AsUTF8String

**Comment by oleavr** [comment] 2015-04-12 11:11
This is due to a mistake on my end where the build machine had the wrong version of Python (UCS-4 instead of UCS-2). This will be fixed in the next release, but in the meantime you can build Frida yourself if you'd like to try it out before then.

Cheers!

**Comment by ling245100108** [comment] 2015-04-12 11:14
Thank you！
When I build frida myself， I meet a error.  I use the build command:
make -f Makefile.linux.mk python-64 PYTHON=/usr/bin/python2.7

error info:

  CXXLD    gum-tests
/home/ling/Desktop/frida/build/sdk-linux-i386/lib/libunwind.a(Los-linux.o): In function `_ULx86_local_resume':
/home/frida/src/frida/build/fs-tmp-linux-i386/libunwind/src/../../../../libunwind/src/x86/Gos-linux.c:304: warning: sigreturn is not implemented and will always fail
/home/ling/Desktop/frida/build/sdk-linux-i386/lib/libv8_base.a(compiler.o): In function `v8::internal::CompilationInfo::LogDeoptCallPosition(int, int)':
compiler.cc:(.text._ZN2v88internal15CompilationInfo20LogDeoptCallPositionEii+0x8c): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/ling/Desktop/frida/build/sdk-linux-i386/lib/libv8_base.a(hydrogen.o): In function `v8::internal::HGraph::SourcePositionToScriptPosition(v8::internal::SourcePosition)':
hydrogen.cc:(.text._ZN2v88internal6HGraph30SourcePositionToScriptPositionENS0_14SourcePositionE+0x63): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/ling/Desktop/frida/build/sdk-linux-i386/lib/libv8_base.a(type-feedback-vector.o): In function `v8::internal::Handle<v8::internal::TypeFeedbackVector> v8::internal::TypeFeedbackVector::Allocate<v8::internal::ZoneFeedbackVectorSpec>(v8::internal::Isolate*, v8::internal::ZoneFeedbackVectorSpec const*)':
type-feedback-vector.cc:(.text._ZN2v88internal18TypeFeedbackVector8AllocateINS0_22ZoneFeedbackVectorSpecEEENS0_6HandleIS1_EEPNS0_7IsolateEPKT_[_ZN2v88internal18TypeFeedbackVector8AllocateINS0_22ZoneFeedbackVectorSpecEEENS0_6HandleIS1_EEPNS0_7IsolateEPKT_]+0x27f): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/ling/Desktop/frida/build/sdk-linux-i386/lib/libv8_base.a(register-allocator.o): In function `v8::internal::compiler::RegisterAllocator::ComputeLiveOut(v8::internal::compiler::InstructionBlock const*)':
register-allocator.cc:(.text._ZN2v88internal8compiler17RegisterAllocator14ComputeLiveOutEPKNS1_16InstructionBlockE+0x182): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/ling/Desktop/frida/build/sdk-linux-i386/lib/libv8_base.a(register-allocator.o): In function `v8::internal::compiler::RegisterAllocator::ResolveControlFlow()':
register-allocator.cc:(.text._ZN2v88internal8compiler17RegisterAllocator18ResolveControlFlowEv+0x2d1): undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/home/ling/Desktop/frida/build/sdk-linux-i386/lib/libv8_base.a(register-allocator.o):register-allocator.cc:(.text._ZN2v88internal8compiler17RegisterAllocator22FindOptimalSpillingPosEPNS1_9LiveRangeENS1_16LifetimePositionE+0x1d8): more undefined references to `std::__throw_out_of_range_fmt(char const*, ...)' follow
collect2: error: ld returned 1 exit status

**Comment by oleavr** [comment] 2015-04-12 11:24
Hmm, it looks like you might have to build the SDK yourself (it was built with GCC 4.9.1, which probably has a newer C++ library that's not ABI compatible with the one you have). To build it, start with a fresh git clone and do:

```sh
$ make -f Makefile.sdk.mk FRIDA_HOST=linux-x86_64
```

**Comment by ling245100108** [comment] 2015-04-12 11:26
Thank you very much! I will have a try!

**Comment by ling245100108** [comment] 2015-04-12 12:20
I have use "make -f Makefile.sdk.mk FRIDA_HOST=linux-x86_64" to build the SDK. 
Success! Here's your SDK: build/sdk-linux-x86_64.tar.bz2
It will be picked up automatically if you now proceed to build Frida.

Then I run the command:"make -f Makefile.linux.mk python-64 PYTHON=/usr/bin/python2.7"

It also the same error. Is there something wrong?

**Comment by oleavr** [comment] 2015-04-12 12:25
Did you start with a freshly cloned git repo? Running "make" just once after cloning will give you a downloaded SDK, so it will not pick up the one you built locally from that point on. (You can also carefully remove it, but let's avoid that to narrow down the potential sources of error.)

**Comment by ling245100108** [comment] 2015-04-13 12:22
I have compiled the _frida.so successfully, and then I use it to replace the so in /usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-x86_64.egg.

Then, I run the python example. It has the following error:
(process:14168): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

**Comment by oleavr** [comment] 2015-04-13 13:00
I don't think that will work, as the latest git has broken the API and ABI for the upcoming 4.0.0 release.

**Comment by oleavr** [comment] 2015-04-13 13:02
Just set your PYTHONPATH to point at your locally compiled version, and add the bin directory to your PATH and you should be all set.

**Comment by oleavr** [comment] 2015-04-13 13:03
Btw: Adding an `install` Makefile.linux.mk target for this would be great if you feel like having a stab at implementing that!

Cheers

**Comment by ling245100108** [comment] 2015-04-13 13:34
I have run the three commands. 
rm -rf /usr/local/lib/python2.7/dist-packages/frida-3.0.1-py2.7-linux-x86_64.egg
export PYTHONPATH=$PYTHONPATH:/home/ling/Desktop/frida/build/frida-linux-x86_64/lib/python2.7/site-packages
export PATH=$PATH:/home/ling/Desktop/frida/build/frida-linux-x86_64/bin

But the error is still exists:
(process:18498): GLib-CRITICAL **: g_variant_new_string: assertion 'string != NULL' failed

**Comment by oleavr** [comment] 2015-04-13 13:37
Ok! This looks like a regression. I'll have a look at it one of the next days (working on finishing everything left for the upcoming release, and this issue is now one of those things). Thanks!

**Comment by oleavr** [comment] 2015-05-30 21:45
The original issue has been fixed. Let's continue discussing the other issues elsewhere if they still exist.

**Closed by oleavr** 2015-05-30 21:45 UTC
